Repository ymzk-jp/javascript-100nocks, pull requests merged in 2018-08, with the labels that each got.

#100 課題29
  answer/itti1021/19_addImage/addImage.js
  answer/itti1021/29_onImage/onImage.css
  answer/itti1021/29_onImage/onImage.html
  answer/itti1021/img/icon_1r_192.png
  answer/itti1021/img/wakaru.jpg
Labels: Review待ち

#101 課題30
  answer/itti1021/30_new/new.css
  answer/itti1021/30_new/new.html
  answer/itti1021/31_createDiv/createDiv.css
  answer/itti1021/31_createDiv/createDiv.html
  answer/itti1021/31_createDiv/createDiv.js
  answer/itti1021/33_3sec/3sec.html
  answer/itti1021/33_3sec/3sec.js
  answer/itti1021/34_wTime/wTime.html
  answer/itti1021/34_wTime/wTime.js
Labels: Review待ち

#102 100nocks NO19
  answer/ahetaro/19/addimage.html
Labels: archive

#104 100nock no20
  answer/ahetaro/20/encrypto1.html
Labels: changeReqest

#110 課題41
  answer/itti1021/41_partOfTable/partOfTable.css
  answer/itti1021/41_partOfTable/partOfTable.html
  answer/itti1021/41_partOfTable/partOfTable.js
  answer/itti1021/42_whichPlace/whichPlace.css
  answer/itti1021/42_whichPlace/whichPlace.html
  answer/itti1021/42_whichPlace/whichPlace.js
Labels: Review待ち

#112 課題 ~50までをやりました
  answer/moya0423/41/partOfTable.html
  answer/moya0423/41/partOfTable.js
  answer/moya0423/42/whichPlace.html
  answer/moya0423/42/whichPlace.js
  answer/moya0423/43/jquery.html
  answer/moya0423/44/incrementHello.html
  answer/moya0423/45/chageColor.html
  answer/moya0423/46/addImageJq.html
  answer/moya0423/47/hasImage.html
  answer/moya0423/48/selectImage.html
  answer/moya0423/49/removeImage.html
  answer/moya0423/img/asyura.jpg
Labels: Review待ち, checked

#113 Itti1021
  answer/itti1021/23_shadow/shadow.css
  answer/itti1021/23_shadow/shadow.html
  answer/itti1021/43_jquery/jquery.html
  answer/itti1021/43_jquery/jquery.js
  answer/itti1021/44_incrementHello/incrementHello.html
  answer/itti1021/44_incrementHello/incrementHello.js
  answer/itti1021/45_chageColor/changeColor.css
  answer/itti1021/45_chageColor/changeColor.html
  answer/itti1021/45_chageColor/changeColor.js
  answer/itti1021/46_addImageJq/addImageJq.html
  answer/itti1021/46_addImageJq/addImageJq.js
  answer/itti1021/47_hasImage/hasImage.html
  answer/itti1021/47_hasImage/hasImage.js
  answer/itti1021/48_selectImage/selectImage.html
  answer/itti1021/48_selectImage/selectImage.js
  answer/itti1021/49_removeImage/removeImage.html
  answer/itti1021/49_removeImage/removeImage.js
Labels: Review待ち, help wanted

#114 微修正
  answer/itti1021/35_randomBgColor/randomBgColor.js
Labels: Review待ち
